Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - ./**/*_spec.rb

Metrics/BlockLength:
  Exclude:
    - ./**/*_spec.rb

Metrics/LineLength:
  Max: 100

Rails:
  Enabled: true

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()

Style/RedundantFreeze:
  Enabled: true

Style/MutableConstant:
  Enabled: false
